# Generated by Django 4.2.4 on 2023-08-17 09:44

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9999999999, verbose_name='Цена')),
                ('paid_status', models.BooleanField(default=False, verbose_name='Платный статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product_status', models.CharField(choices=[('process', 'В процесе'), ('shipped', 'Отправленный'), ('delivered', 'Доставленный')], default='process', max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина заказа',
                'verbose_name_plural': 'Корзина заказов',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cit', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=20, prefix='cat', unique=True, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(default='category.jpg', upload_to='category', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Катогоия',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=20, prefix='', unique=True, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(default='product.jpg', upload_to=core.models.user_directory_path, verbose_name='Картинка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9999999999, verbose_name='Цена')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=9999999999, verbose_name='Старая цена')),
                ('specifications', models.TextField(blank=True, null=True, verbose_name='Характеристики')),
                ('product_status', models.CharField(choices=[('draft', 'В черновике'), ('disabled', 'Откленен'), ('rejected', 'Отменен'), ('in_review', 'На Расмотрении'), ('published', 'Опубликованно')], default='in_review', max_length=10, verbose_name='Статус продукта')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('in_stock', models.BooleanField(default=True, verbose_name='Есть в наличии')),
                ('featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('digital', models.BooleanField(default=False, verbose_name='Цифровой')),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=4, max_length=10, prefix='', unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновление')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Список желаний',
                'verbose_name_plural': 'Списки желаний',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=20, prefix='ven', unique=True, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Имя')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('contact', models.CharField(max_length=100, verbose_name='Контакты')),
                ('chat_resp_time', models.CharField(max_length=100, verbose_name='Время для чата')),
                ('shipping_on_time', models.CharField(max_length=100, verbose_name='Время доставки')),
                ('authentic_rating', models.CharField(max_length=100, verbose_name='Подлинный рейтинг')),
                ('days_return', models.CharField(max_length=100, verbose_name='Дата возврата')),
                ('warranty_period', models.CharField(max_length=100, verbose_name='Гарантийный период')),
                ('image', models.ImageField(default='vendor.jpg', upload_to=core.models.user_directory_path, verbose_name='Картинка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='Текст')),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=None, verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обзор продукта',
                'verbose_name_plural': 'Обзоры продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product-image', verbose_name='Изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'Изображения продуктов',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tag', verbose_name='Тегы'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vendor', verbose_name='Поставщик'),
        ),
        migrations.CreateModel(
            name='CartOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_status', models.CharField(max_length=200, verbose_name='Статус')),
                ('item', models.CharField(max_length=200, verbose_name='Элемент')),
                ('invoice_number', models.CharField(max_length=200, verbose_name='Номер счета')),
                ('image', models.CharField(max_length=200, verbose_name='Изображения')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9999999999, verbose_name='Цена')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9999999999, verbose_name='Общий')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cartorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Товар заказа в корзине',
                'verbose_name_plural': 'Товары для заказа в корзине',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Адрес')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
