# Generated by Django 4.2.4 on 2023-08-18 18:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(default='product.jpg', upload_to=core.models.user_directory_path, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='cover_product.jpg', upload_to=core.models.user_directory_path, verbose_name='Изображение обложки'),
        ),
    ]
