# Generated by Django 4.2.4 on 2023-08-18 18:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_cover_image_vendor_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='cover_product.jpg', upload_to=core.models.user_directory_path, verbose_name='Изображение обложки'),
        ),
    ]
