# Generated by Django 4.2.4 on 2023-08-21 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_language'),
        ('core', '0007_alter_vendor_cover_image'),
    ]

    operations = [
    ]
