# Generated by Django 4.2.4 on 2023-08-21 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20230821_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='language',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.product', verbose_name='Продукт'),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
