# Generated by Django 4.2.4 on 2023-08-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_category_language_alter_productimage_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='life',
            field=models.DateField(blank=True, null=True, verbose_name='Срок годности'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип продукта'),
        ),
    ]
